services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb+srv://gaelandres2005:Kxw5xuxpQddZKaBQ@cluster0.mgibr.mongodb.net/educational_dashboard?retryWrites=true&w=majority&appName=Cluster0 # Change database name
      - JWT_SECRET=your_jwt_secret_key_here # Change to your own secret
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000 # Change if necessary.
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
